---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=600
  when: ansible_os_family == 'Debian'

- name: Install mysql package dependencies
  ansible.builtin.package:
    name: '{{ _mysql_dependencies }}'
    state: present
  become: true
  register: install_mysql_dependencies
  when: _mysql_dependencies is defined
  tags:
    - install
    - apt
    - update_cache
