---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=600
  when: ansible_os_family == 'Debian'

- name: Install mysql package dependencies
  ansible.builtin.package:
    name: '{{ mysql_packages }}'
    state: present
  become: true
  register: install_mysql_packages
  when: mysql_packages is defined
  tags:
    - install
    - apt
    - update_cache
