---
# Variable configuration.
- name: Include OS-specific variables.
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - 'vars/{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml'
        - 'vars/{{ ansible_os_family | lower }}.yml'
      skip: true
  tags:
    - 'mysql'
    - 'mysql-vars'
