---
- name: Include vars by operating system.
  import_tasks: include_vars.yml

# Variable configuration.
- include_tasks: variables.yml

- name: Install dependencies
  import_tasks: dependences.yml
  when:
    - mysql_only_deploy == False

- name: Implement task templates
  import_tasks: templates.yml

- name: Implement task install
  import_tasks: install.yml
  when:
    - mysql_only_deploy == False

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages:
      '{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}'

# Configure MySQL.
- include_tasks: configure.yml
- include_tasks: secure-installation.yml
- include_tasks: databases.yml
- include_tasks: users.yml
- include_tasks: replication.yml

- name: Implement task post-install
  import_tasks: post-install.yml
