---
- name: Include vars by operating system.
  import_tasks: include_vars.yml

- name: Define mysql_daemon.
  set_fact:
    mysql_daemon: '{{ _mysql_daemon }} '
  when: mysql_daemon is not defined

- name: Install dependencies
  import_tasks: dependences.yml
  when:
    - mysql_only_deploy == False

- name: Install Or Update files
  import_tasks: files.yml
  when:
    - mysql_only_deploy == False

- name: Install Or Update host
  import_tasks: host.yml
  when:
    - mysql_only_deploy == False

- name: Implement task templates
  import_tasks: templates.yml

- name: Implement task environment
  import_tasks: environment.yml

- name: Implement task install
  import_tasks: install.yml
  when:
    - mysql_only_deploy == False

- name: implement configure
  import_tasks: configure.yml
  when:
    - mysql_only_deploy == False

- name: implement secure installation
  import_tasks: secure_installation.yml
  when:
    - mysql_only_deploy == False

- name: Implement task post install
  import_tasks: post_install.yml
